# Dependencias
FROM node:20-alpine3.19 AS deps
WORKDIR /usr/src/app
COPY package*.json ./
COPY prisma ./prisma
RUN npm install

# Builder
FROM node:20-alpine3.19 AS builder
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .
RUN npm run build
RUN npx prisma generate
# Debug opcional: verificar que sí exista el main.js
#RUN test -f dist/main.js || (echo "❌ No existe dist/main.js" && ls -R dist && exit 1)

# Producción
FROM node:20-alpine3.19 AS prod
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "dist/main.js"]